#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v3
# autospec commit: fae1327
#
Name     : zxcvbn-c
Version  : 2.5
Release  : 2
URL      : https://github.com/tsyrogit/zxcvbn-c/archive/refs/tags/v2.5.tar.gz
Source0  : https://github.com/tsyrogit/zxcvbn-c/archive/refs/tags/v2.5.tar.gz
Summary  : A library for password entropy checking
Group    : Development/Tools
License  : MIT
Requires: zxcvbn-c-bin = %{version}-%{release}
Requires: zxcvbn-c-data = %{version}-%{release}
Requires: zxcvbn-c-lib = %{version}-%{release}
Requires: zxcvbn-c-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: make.patch

%description
This is a library for password entropy checks based on common names, words and
patterns in US English.

%package bin
Summary: bin components for the zxcvbn-c package.
Group: Binaries
Requires: zxcvbn-c-data = %{version}-%{release}
Requires: zxcvbn-c-license = %{version}-%{release}

%description bin
bin components for the zxcvbn-c package.


%package data
Summary: data components for the zxcvbn-c package.
Group: Data

%description data
data components for the zxcvbn-c package.


%package dev
Summary: dev components for the zxcvbn-c package.
Group: Development
Requires: zxcvbn-c-lib = %{version}-%{release}
Requires: zxcvbn-c-bin = %{version}-%{release}
Requires: zxcvbn-c-data = %{version}-%{release}
Provides: zxcvbn-c-devel = %{version}-%{release}
Requires: zxcvbn-c = %{version}-%{release}

%description dev
dev components for the zxcvbn-c package.


%package lib
Summary: lib components for the zxcvbn-c package.
Group: Libraries
Requires: zxcvbn-c-data = %{version}-%{release}
Requires: zxcvbn-c-license = %{version}-%{release}

%description lib
lib components for the zxcvbn-c package.


%package license
Summary: license components for the zxcvbn-c package.
Group: Default

%description license
license components for the zxcvbn-c package.


%prep
%setup -q -n zxcvbn-c-2.5
cd %{_builddir}/zxcvbn-c-2.5
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706903394
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1706903394
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zxcvbn-c
cp %{_builddir}/zxcvbn-c-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/zxcvbn-c/ea25421833f68a72196dbfec95f6e2f5f7d3a383 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dictgen

%files data
%defattr(-,root,root,-)
/usr/share/zxcvbn/zxcvbn.dict

%files dev
%defattr(-,root,root,-)
/usr/include/dict-crc.h
/usr/include/dict-src.h
/usr/include/zxcvbn.h
/usr/lib64/libzxcvbn.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzxcvbn.so.0
/usr/lib64/libzxcvbn.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zxcvbn-c/ea25421833f68a72196dbfec95f6e2f5f7d3a383
